name: E2E in docker container
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Docker image with Cypress pre-installed
    # https://github.com/cypress-io/cypress-docker-images/tree/master/included
    container: lucky-sloth-2-frontend_nextjs_1
    steps:
      - uses: actions/checkout@v1
      - run: cypress run
